name = "SimpleCrop"
uuid = "d8d364f4-8e31-46ec-8830-5c8affd8de2c"
authors = ["Kyungdahm Yun <tomyun@gmail.com>"]

[deps]
Cropbox = "a904b226-abf1-11e9-2713-059ba252a964"

[compat]
Cropbox = "0.3"
julia = "1.6"
